name: Build SimpleHomes Plugin

on:
  push:
    paths:
      - 'simple-homes-plugin/**'
      - '.github/workflows/simple-homes-plugin.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: simple-homes-plugin
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload jar
        uses: actions/upload-artifact@v7
        with:
          name: SimpleHomes
          path: simple-homes-plugin/build/libs/SimpleHomes-*.jar
